"""seed trails and hikers

Revision ID: b0b9d1bbf050
Revises: 24aff6b6de05
Create Date: 2024-12-13 12:40:53.698825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0b9d1bbf050'
down_revision = '24aff6b6de05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hikers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('dog_friendly', sa.Boolean(), nullable=True),
    sa.Column('park_id', sa.Integer(), nullable=False),
    sa.Column('hiker_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hiker_id'], ['hikers.id'], name=op.f('fk_trails_hiker_id_hikers')),
    sa.ForeignKeyConstraint(['park_id'], ['parks.id'], name=op.f('fk_trails_park_id_parks')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trails')
    op.drop_table('hikers')
    # ### end Alembic commands ###
